_wandb:
    value:
        cli_version: 0.25.1
        e:
            h9o7z7v8lfklylygpt9dvfcxfkryejkg:
                args:
                    - --cot_mode
                    - continuous
                    - --n_thought_steps
                    - "4"
                    - --max_stages
                    - "10"
                    - --max_steps
                    - "50"
                    - --n_train
                    - "10000"
                    - --n_val
                    - "1000"
                    - --save_dir
                    - ../figures
                    - --device
                    - cuda
                    - --wandb_entity
                    - emiletimothyanand
                    - --wandb_project
                    - transformers_online_decision_makers
                    - --wandb_run_name
                    - cuda-20260402-032512
                codePath: multiplicative_weights/scripts/gradient_train_transformer_for_mwu.py
                codePathLocal: gradient_train_transformer_for_mwu.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "53607378944"
                        used: "26645291008"
                email: emiletimothy@outlook.com
                executable: /home/ec2-user/transformer_decisionmaker/venv/bin/python3
                git:
                    commit: cf911b2c8944618ccfafc691d2927ed01ecdf189
                    remote: https://github.com/emiletimothy/transformer_decisionmaker.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-7022110b-6989-f954-e2d2-da0274311780
                host: ip-172-31-11-157.us-east-2.compute.internal
                memory:
                    total: "33267298304"
                os: Linux-6.1.163-186.299.amzn2023.x86_64-x86_64-with-glibc2.34
                program: /home/ec2-user/transformer_decisionmaker/multiplicative_weights/scripts/gradient_train_transformer_for_mwu.py
                python: CPython 3.9.25
                root: /home/ec2-user/transformer_decisionmaker/multiplicative_weights/scripts
                startedAt: "2026-04-02T03:25:15.813051Z"
                writerId: h9o7z7v8lfklylygpt9dvfcxfkryejkg
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.9.25
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 32
cot_mode:
    value: continuous
d_model:
    value: 64
device:
    value: cuda
early_stopping_patience:
    value: 12
learning_rate:
    value: 0.0003
max_epochs_per_stage:
    value: 30
max_stages:
    value: 10
max_steps:
    value: 50
n_experts:
    value: 4
n_heads:
    value: 4
n_layers:
    value: 2
n_params:
    value: 214587
n_thought_steps:
    value: 4
n_train:
    value: 10000
n_val:
    value: 1000
